settings:
  metrics: true # Включение/отключение системы метрик
  update-check: true # Проверять наличие обновлений при запуске сервера?
  distance-dangs: 100 # Максимальное расстояние до спавна данжа